services:
  app:
    build:
      context: .  # Build from the Dockerfile in the current directory
      args:
        mode: dev 
    container_name: app_container
    environment:
      - LOG_LEVEL=debug
    env_file:
      - .env
    ports: 
      - "8000:8000"
    volumes: 
      - ./app-volume:/app  # Any changes made in the /app-volume dir locally will reflect in the app container instantly
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] # this helps to Post data with the CURL command outside of the container 
    depends_on:
      - db 
    networks:
      app_network:
        aliases:
          - app

  db:
    image: postgres:13
    container_name: db_container
    env_file:
      - .env
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      app_network:
        aliases:
          - database

volumes:
  db_data:

networks:
  app_network: # Shared network for communication between containers
